//
// Created by 86159 on 2025/1/2.
//

#include "myRobot.h"

void Robot_Leg_Choose(uint8_t idx){
//    HAL_GPIO_WritePin(MY_ROBOT_CHOOSE_PORT_AB, MY_ROBOT_CHOOSE_PIN_A, (idx & 0x01)?GPIO_PIN_SET:GPIO_PIN_RESET);
//    HAL_GPIO_WritePin(MY_ROBOT_CHOOSE_PORT_AB, MY_ROBOT_CHOOSE_PIN_B, (idx & 0x02)?GPIO_PIN_SET:GPIO_PIN_RESET);
//    HAL_GPIO_WritePin(MY_ROBOT_CHOOSE_PORT_C, MY_ROBOT_CHOOSE_PIN_C, (idx & 0x04)?GPIO_PIN_SET:GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MY_ROBOT_GPIO_Port, MY_ROBOT_CHOOSE_PIN_A, (idx & 0x01)?GPIO_PIN_SET:GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MY_ROBOT_GPIO_Port, MY_ROBOT_CHOOSE_PIN_B, (idx & 0x02)?GPIO_PIN_SET:GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MY_ROBOT_GPIO_Port, MY_ROBOT_CHOOSE_PIN_C, (idx & 0x04)?GPIO_PIN_SET:GPIO_PIN_RESET);
}

void Robot_Leg_PWM(uint16_t pwm){
            __HAL_TIM_SetCompare(&htim_advance, MY_PWM_CHANNEL, pwm);
}

void Robot_Init(){
//    MY_ROBOT_CHOOSE_AB_CLK_ENABLE();
//    MY_GPIO_INIT(MY_ROBOT_CHOOSE_PORT_AB, MY_ROBOT_CHOOSE_PIN_A);
//    MY_GPIO_INIT(MY_ROBOT_CHOOSE_PORT_AB, MY_ROBOT_CHOOSE_PIN_B);
//    MY_ROBOT_CHOOSE_C_CLK_ENABLE();
//    MY_GPIO_INIT(MY_ROBOT_CHOOSE_PORT_C, MY_ROBOT_CHOOSE_PIN_C);


    MX_TIM_Advance_Init();   // 初始化高级定时器 - 用于PWM
    HAL_TIM_PWM_Start(&htim_advance, MY_PWM_CHANNEL);    /* 开启 PWM 通道 1 */
}
